#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: Abnahmelauf zu Issue #426 (Lernschleife und Widerspruchspruefung)
#
# Fuehrt durch zwei Codex-Sitzungen gegen die Spike-Instanz und wertet beide
# objektiv aus (logstore_standard_log + Ablagedatei). Der Wizard fasst Moodle
# nur fuer Aufbau und Auswertung an - den Lauf selbst macht Codex.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=9

MOODLE_URL="${MOODLE_URL:-https://spike.gruenwald.fun}"
MCP_URL="$MOODLE_URL/local/coursepilot/mcp.php"
CONTAINER="${KURSPILOT_SPIKE_CONTAINER:-moodle-kurspilot-spike-webserver-1}"
SPIKE_USER="${KURSPILOT_SPIKE_USERNAME:-teacher_edit}"
COURSE_ID="${MOODLE_TEST_COURSEID:-6}"
QTYPE="${QTYPE:-ddwtos}"
REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
WORKDIR="${WORKDIR:-$REPO/.abnahme-426}"
CODEX_CONFIG="$HOME/.codex/config.toml"

mkdir -p "$WORKDIR"

# spike_php SNIPPET_FILE [ARGS...] fuehrt PHP im Spike-Container aus, mit dem
# Testnutzer als $USER - so gelten dieselben Pfadregeln wie fuer die Werkzeuge.
spike_php() {
  local snippet="$1"; shift
  docker exec -i "$CONTAINER" php -- "$SPIKE_USER" "$@" < "$snippet"
}

# Ein Praeambel-Block, den jedes Snippet oben einbindet: Moodle laden und den
# Testnutzer anmelden.
cat > "$WORKDIR/_prelude.php" <<'PHP'
<?php
define('CLI_SCRIPT', true);
require('/var/www/html/config.php');
$user = $DB->get_record('user', ['username' => $argv[1], 'deleted' => 0], '*', MUST_EXIST);
\core\session\manager::set_user($user);
PHP

# _snippet NAME <<'PHP' ... PHP  baut ein lauffaehiges Snippet aus Praeambel + Rumpf.
_snippet() {
  local name="$1"
  cat "$WORKDIR/_prelude.php" > "$WORKDIR/$name.php"
  cat >> "$WORKDIR/$name.php"
}

_snippet ctx_list <<'PHP'
$ctx = \local_coursepilot\context_files::own_context();
$fs = get_file_storage();
foreach ($fs->get_area_files($ctx->id, 'user', 'private', 0, 'filepath, filename', false) as $f) {
    printf("%s%s\t%s\t%s\n", $f->get_filepath(), $f->get_filename(),
        userdate($f->get_timemodified(), '%Y-%m-%d %H:%M'), substr($f->get_contenthash(), 0, 8));
}
PHP

_snippet ctx_get <<'PHP'
$ctx = \local_coursepilot\context_files::own_context();
[$dir, $name] = \local_coursepilot\context_files::resolve_file($argv[2]);
$f = get_file_storage()->get_file($ctx->id, 'user', 'private', 0, $dir, $name);
if (!$f) { fwrite(STDERR, "nicht vorhanden: $dir$name\n"); exit(1); }
echo $f->get_content();
PHP

_snippet ctx_put <<'PHP'
$ctx = \local_coursepilot\context_files::own_context();
[$dir, $name] = \local_coursepilot\context_files::resolve_writable_file($argv[2]);
// get_file() liefert false, replace() erwartet ?stored_file.
$existing = get_file_storage()->get_file($ctx->id, 'user', 'private', 0, $dir, $name) ?: null;
\local_coursepilot\context_files::replace($existing,
    \local_coursepilot\context_files::filerecord($ctx->id, $dir, $name),
    base64_decode($argv[3]));
echo "geschrieben: $dir$name\n";
PHP

# Loescht per rohem Moodle-Dateipfad (z.B. /kurspilot/fragetypen/ddwtos.md),
# damit auch der Fehlpfad aus #425 F1 (/kurspilot/kurspilot/...) raeumbar ist.
_snippet ctx_delete <<'PHP'
$ctx = \local_coursepilot\context_files::own_context();
$dir = dirname($argv[2]) . '/';
$f = get_file_storage()->get_file($ctx->id, 'user', 'private', 0, $dir, basename($argv[2]));
if (!$f) { echo "nicht vorhanden: {$argv[2]}\n"; exit(0); }
$f->delete();
echo "geloescht: {$argv[2]}\n";
PHP

_snippet log_tools <<'PHP'
$since = (int) $argv[2];
$rows = $DB->get_records_select('logstore_standard_log',
    'component = :c AND timecreated >= :t', ['c' => 'local_coursepilot', 't' => $since],
    'timecreated ASC', 'id, timecreated, eventname, other');
foreach ($rows as $r) {
    $other = json_decode((string) $r->other, true);
    if (!is_array($other)) { $other = @unserialize((string) $r->other) ?: []; }
    $failed = str_contains($r->eventname, 'failed');
    // Bei Fehlversuchen traegt 'reason' den Grund - das ist der Beleg dafuer,
    // was Kurspilot je Versuch berichten musste. toolname ist dort null, wenn
    // der Aufruf schon vor der Werkzeugwahl scheiterte (z.B. Method not found).
    $reason = $failed ? '  ' . preg_replace('/\s+/', ' ', substr((string) ($other['reason'] ?? ''), 0, 110)) : '';
    printf("%s  %-30s %-6s%s\n", userdate($r->timecreated, '%H:%M:%S'),
        $other['toolname'] ?? '-', $failed ? 'FEHLER' : 'ok', $reason);
}
if (!$rows) { echo "(keine Werkzeugaufrufe im Zeitfenster)\n"; }
PHP

banner "Abnahme #426 - Lernschleife und Widerspruchspruefung"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Vorbedingungen"
say "Der Lauf prueft Skill-Regeln gegen den ausgerollten Plugin-Stand."
if ! docker ps --format '{{.Names}}' | grep -qx "$CONTAINER"; then
  warn "Container '$CONTAINER' laeuft nicht - Spike-Stack starten und neu beginnen."
  exit 1
fi
note "Container '$CONTAINER' laeuft."
say ""
step "Skills und Plugin muessen dem Repo-Stand entsprechen (Fix aus #425 ist in 44dfd3c)."
note "Repo-HEAD: $(git -C "$REPO" log --oneline -1)"
if confirm "Plugin jetzt neu ausrollen (deploy-plugin-spike.sh, laeuft upgrade.php)?"; then
  bash "$REPO/scripts/deploy-plugin-spike.sh"
  pause "Deploy durch. Weiter?"
else
  note "Uebersprungen - dann muss der letzte Deploy den HEAD-Stand tragen."
fi
say ""
warn "Vor dem Lauf einen Rollback-Punkt setzen (die Laeufe schreiben in Kurs $COURSE_ID):"
note "  bash /opt/kurspilot-spike/scripts/rollback.sh snapshot"
pause "Snapshot gesetzt oder bewusst verzichtet?"

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Codex an das Server-MCP anbinden"
say "Das Plugin ist ein OAuth-2.1-Server (classes/oauth_lib.php): Codex meldet"
say "sich per Browser-Flow an, du gibst die Freigabe in Moodle, Codex haelt das"
say "Token-Paar selbst (Access 1 h, Refresh 30 Tage) und erneuert es selbst."
say ""
warn "Diese Stage betrifft nur die Maschine, auf der Codex laeuft."
note "Laeuft Codex auf einem anderen Rechner (z.B. Laptop) - hier 'n' und den"
note "Eintrag dort setzen. Steht er dort schon und funktioniert, ist nichts zu tun."
say ""
warn "Der Browser-Flow muss als '$SPIKE_USER' autorisiert werden."
note "Die Fragetyp-Ablage liegt in den Private Files des angemeldeten Nutzers -"
note "meldest du dich als jemand anderes an, wertet dieser Wizard den falschen"
note "Bereich aus und sieht nichts."
say ""
if grep -q 'mcp_servers.kurspilot' "$CODEX_CONFIG" 2>/dev/null; then
  note "In $CODEX_CONFIG existiert bereits ein Eintrag [mcp_servers.kurspilot]:"
  sed -n '/\[mcp_servers.kurspilot\]/,/^\[/p' "$CODEX_CONFIG" | sed '$d' | sed 's/^/    /'
  pause "Stimmt er noch? Weiter."
else
  warn "Kein [mcp_servers.kurspilot] in $CODEX_CONFIG gefunden."
  say "Vorschlag fuer den Fall, dass Codex hier laufen soll - Schluesselnamen"
  say "gegen die Codex-Version gegenpruefen, sie haben sich zwischen Releases"
  say "geaendert. Kann Codex den OAuth-Flow selbst, entfaellt der Bearer-Teil:"
  cat <<TOML | sed 's/^/    /'

[mcp_servers.kurspilot]
url = "$MCP_URL"
bearer_token_env_var = "KURSPILOT_TOKEN"
experimental_use_rmcp_client = true
TOML
  say ""
  if confirm "Diesen Block an $CODEX_CONFIG anhaengen?"; then
    {
      printf '\n[mcp_servers.kurspilot]\nurl = "%s"\n' "$MCP_URL"
      printf 'bearer_token_env_var = "KURSPILOT_TOKEN"\nexperimental_use_rmcp_client = true\n'
    } >> "$CODEX_CONFIG"
    note "angehaengt."
  else
    SKIPPED+=("Codex-MCP-Eintrag in $CODEX_CONFIG von Hand setzen")
  fi
fi

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Rauchprobe: traegt der ausgerollte Stand das Versionswerkzeug?"
say "Diese Probe gehoert dem Wizard, nicht der Codex-Sitzung: sie prueft vorab,"
say "ob coursepilot_get_version_info ueberhaupt da ist. Fehlt es, ist Pruefpunkt 2"
say "nicht durchfuehrbar - besser jetzt gemerkt als mitten im Lauf."
say ""
TOKEN="$(bash "$REPO/scripts/spike-e2e-token.sh" "$SPIKE_USER")"
[[ -n "$TOKEN" ]] || { warn "Kein Token erhalten."; exit 1; }
note "Token fuer die Probe ausgestellt (ersetzt den Browser-Flow, gilt eine Stunde)."
TOOLS="$(curl -s -X POST "$MCP_URL" -H "Authorization: Bearer $TOKEN" \
  -H 'Content-Type: application/json' \
  -d '{"jsonrpc":"2.0","id":1,"method":"tools/list"}')"
if grep -q 'coursepilot_get_version_info' <<<"$TOOLS"; then
  note "tools/list antwortet, coursepilot_get_version_info ist da (Voraussetzung fuer Pruefpunkt 2)."
else
  warn "coursepilot_get_version_info fehlt in tools/list - Plugin-Stand ist zu alt."
  exit 1
fi
say ""
note "Nur falls Codex hier mit statischem Bearer statt OAuth angebunden ist:"
printf '\n    export KURSPILOT_TOKEN=%s\n\n' "$TOKEN"
printf 'export KURSPILOT_TOKEN=%s\n' "$TOKEN" > "$WORKDIR/token.env"
note "Abgelegt in $WORKDIR/token.env. Bei OAuth-Anbindung ignorieren."
pause "Weiter"

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Ausgangszustand: Fragetyp-Ablage leeren"
say "Die Lernschleife startet nur, wenn es fuer '$QTYPE' noch keine Ablage gibt."
say "Bestand im Kontextbereich von $SPIKE_USER:"
say ""
spike_php "$WORKDIR/ctx_list.php" | grep -i 'fragetypen' | sed 's/^/    /' || note "    (nichts unter fragetypen/)"
say ""
step "Weg muss: /kurspilot/fragetypen/$QTYPE.md - sonst wird Schritt 1 der"
step "Lernschleife bedient statt sie auszuloesen."
step "Weg darf auch: /kurspilot/kurspilot/... - der Fehlpfad aus #425 F1."
say ""
if confirm "Diese beiden Pfade jetzt loeschen (nicht rueckholbar)?"; then
  spike_php "$WORKDIR/ctx_delete.php" "/kurspilot/fragetypen/$QTYPE.md" | sed 's/^/    /'
  spike_php "$WORKDIR/ctx_delete.php" "/kurspilot/kurspilot/fragetypen/match.md" | sed 's/^/    /'
else
  warn "Nicht geloescht - Pruefpunkt 1 laeuft dann ins Leere."
fi
pause "Weiter"

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Lauf A: Prompt einspielen und Codex arbeiten lassen"
T0="$(date +%s)"
printf '%s\n' "$T0" > "$WORKDIR/t0-lauf-a"
{
  printf '%s\n\n---\n\n' "$(cat "$REPO/skills/spike-kontextbereich.md")"
  printf '%s\n\n---\n\n' "$(cat "$REPO/skills/spike-fragetypen.md")"
  cat <<PROMPT
# Auftrag

Lege im Moodle-Kurs mit der ID $COURSE_ID eine Frage vom Typ \`$QTYPE\`
(Drag-and-drop in Text) in der Fragenbank an. Nutze dafuer ausschliesslich die
Kurspilot-Werkzeuge des MCP-Servers.

Die beiden Regelwerke oben gelten fuer diese Sitzung vollstaendig.
PROMPT
} > "$WORKDIR/prompt-lauf-a.md"
say "Prompt-Paket geschrieben (beide Regelwerke + Auftrag):"
note "  $WORKDIR/prompt-lauf-a.md"
say ""
step "Neue Codex-Sitzung oeffnen - eine eigene, nicht diese Entwicklungssitzung."
step "Inhalt der Datei oben als ersten Prompt einspielen."
step "Die Sitzung normal fuehren: Rueckfragen beantworten, Schreibangebote"
step "  bestaetigen. Nichts vorsagen, was Kurspilot selbst herausfinden soll."
say ""
warn "Waehrend des Laufs im Gespraechsverlauf mitlesen (Pruefpunkt 3, aus dem Log nicht ablesbar):"
note "  - wird der unbekannte Fragetyp vorab angesagt?"
note "  - wird je Fehlversuch berichtet, was fehlschlug und was korrigiert wurde?"
note "  - kommt nach dem dritten Fehlschlag die Vorlagenanforderung?"
say ""
pause "Lauf A beendet? Dann Enter fuer die Auswertung."

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Lauf A auswerten"
say "Werkzeug-Verlauf aus logstore_standard_log (objektiv, seit Lauf-A-Start):"
say ""
spike_php "$WORKDIR/log_tools.php" "$T0" | sed 's/^/    /'
say ""
step "Pruefpunkt 1 - kamen Fehlversuche vor? (FEHLER-Zeilen bei import_questions_xml)"
step "Pruefpunkt 1 - hoechstens drei Importversuche, danach Schluss?"
step "Schritt 2 der Lernschleife - taucht export_questions_xml auf?"
say ""
say "Ablagedatei nach dem Lauf:"
say ""
spike_php "$WORKDIR/ctx_list.php" | grep -i 'fragetypen' | sed 's/^/    /' || warn "    keine Ablagedatei entstanden"
say ""
step "Pruefpunkt 4 - liegt sie unter /kurspilot/fragetypen/$QTYPE.md?"
step "  Ein zweites 'kurspilot/' im Pfad ist der Rueckfall von #425 F1."
if spike_php "$WORKDIR/ctx_get.php" "fragetypen/$QTYPE.md" > "$WORKDIR/ablage-lauf-a.md" 2>/dev/null; then
  note "Inhalt gesichert: $WORKDIR/ablage-lauf-a.md"
  say ""
  say "Kopf der Datei:"
  head -12 "$WORKDIR/ablage-lauf-a.md" | sed 's/^/    /'
  step "Stehen echte Versionsangaben im Kopf, kein 'nicht ermittelt'? (#425 F3)"
  step "Ist das Minimal-Beispiel die tatsaechlich importierte XML inkl. <quiz>-Rahmen? (#425 F2)"
else
  warn "Keine Ablage unter fragetypen/$QTYPE.md - Schritt 6 der Lernschleife nicht erfuellt."
fi
say ""
pause "Befunde notiert? Weiter zur Widerspruchspruefung."

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Widerspruch einbauen"
say "Fuer Pruefpunkt 2 wird die Ablagedatei von Hand verfaelscht: eine"
say "dokumentierte Regel ins Gegenteil verkehrt, Versionsstand im Kopf alt."
if [[ ! -s "$WORKDIR/ablage-lauf-a.md" ]]; then
  warn "Keine Ablage aus Lauf A vorhanden - Pruefpunkt 2 ist so nicht pruefbar."
  SKIPPED+=("Pruefpunkt 2 (Widerspruchspruefung) - keine Ablagedatei aus Lauf A")
  pause "Weiter"
else
  cp "$WORKDIR/ablage-lauf-a.md" "$WORKDIR/ablage-verfaelscht.md"
  say ""
  step "Datei jetzt im Editor oeffnen und zwei Dinge aendern:"
  note "  1. Im Kopf einen deutlich aelteren Moodle-/Plugin-Versionsstand eintragen."
  note "  2. Eine Regel unter 'Pflichtstruktur' oder 'Stolpersteine' ins Gegenteil"
  note "     verkehren - so, dass ein Bau nach dieser Datei sichtbar scheitert."
  note "     (z.B. den <quiz>-Rahmen als 'darf nicht gesetzt werden' auszeichnen)"
  say ""
  note "  $WORKDIR/ablage-verfaelscht.md"
  pause "Datei verfaelscht und gespeichert?"
  if confirm "Verfaelschte Fassung auf die Instanz zurueckschreiben?"; then
    spike_php "$WORKDIR/ctx_put.php" "fragetypen/$QTYPE.md" \
      "$(base64 -w0 < "$WORKDIR/ablage-verfaelscht.md" 2>/dev/null || base64 < "$WORKDIR/ablage-verfaelscht.md" | tr -d '\n')" \
      | sed 's/^/    /'
  else
    SKIPPED+=("verfaelschte Ablage zurueckschreiben - Pruefpunkt 2 offen")
  fi
fi

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "Lauf B: Widerspruchspruefung"
T1="$(date +%s)"
printf '%s\n' "$T1" > "$WORKDIR/t0-lauf-b"
sed "s/in der Fragenbank an\./in der Fragenbank an - eine zweite, inhaltlich andere Frage desselben Typs./" \
  "$WORKDIR/prompt-lauf-a.md" > "$WORKDIR/prompt-lauf-b.md"
say "Prompt-Paket fuer Lauf B geschrieben:"
note "  $WORKDIR/prompt-lauf-b.md"
say ""
step "Wieder eine frische Codex-Sitzung - keine Fortsetzung von Lauf A,"
step "  sonst weiss das Modell die Wahrheit noch aus dem Kontext."
say ""
warn "Erwartet wird eine ausdrueckliche Widerspruchsmeldung:"
note "  - benennt die Abweichung zwischen Datei und tatsaechlichem Verhalten"
note "  - nennt eine Ursachenvermutung (z.B. neue Moodle-/Plugin-Version)"
note "  - bietet an, den betroffenen Abschnitt zu ueberarbeiten"
note "  - kein stilles Weiterarbeiten gegen die Datei"
say ""
pause "Lauf B beendet? Dann Enter."
say ""
say "Werkzeug-Verlauf Lauf B:"
say ""
spike_php "$WORKDIR/log_tools.php" "$T1" | sed 's/^/    /'
say ""
step "Wurde die Ablage vor dem Bau gelesen? (read_context_file zu Beginn)"
step "Wurde sie nach Zustimmung ueberarbeitet? (write_context_file, Versionskopf aktuell)"
spike_php "$WORKDIR/ctx_get.php" "fragetypen/$QTYPE.md" > "$WORKDIR/ablage-lauf-b.md" 2>/dev/null \
  && note "Endstand gesichert: $WORKDIR/ablage-lauf-b.md"
pause "Weiter zum Abschluss."

# ── 9 ─────────────────────────────────────────────────────────────────────
stage "Befunde an #426 melden"
say "Alle Belege liegen in $WORKDIR:"
ls -1 "$WORKDIR" | grep -vE '\.php$' | sed 's/^/    /'
say ""
step "Befunde je Pruefpunkt (1-4) formulieren, Muster: Symptom, Beleg aus dem"
step "  Werkzeug-Verlauf, Fix-Vorschlag am Skill - wie in #425."
say ""
if confirm "Jetzt einen Kommentar an Issue #426 schreiben (oeffnet \$EDITOR)?"; then
  gh issue comment 426 --repo matthiasgruenwald/Kurspilot --editor \
    || SKIPPED+=("Kommentar an #426 - gh-Aufruf fehlgeschlagen")
else
  SKIPPED+=("Befunde an #426 kommentieren")
fi
say ""
warn "Vor dem Aufraeumen: $WORKDIR enthaelt ein gueltiges Zugriffstoken."
note "  rm -rf $WORKDIR   (das Token verfaellt ohnehin nach einer Stunde)"

finish
