<?php
// This file is part of Coursepilot, a plugin for Moodle - http://moodle.org/
//
// Coursepilot is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Coursepilot is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with Coursepilot.  If not, see <https://www.gnu.org/licenses/>.

namespace local_coursepilot;

/**
 * Privacy contract of the Coursepilot surface (card #289, ticket #300).
 *
 * Coursepilot exposes teacher-related course design only. Data generated by
 * learners or personal data (submissions, forum posts,
 * quiz attempts, grades, participant lists) is reachable neither via MCP tools
 * nor via Moodle web services.
 *
 * One check function, three callers (#300, points 1/5/6):
 *  - Test:     tests/privacy_surface_test.php checks against the really
 *              registered surface of a running instance.
 *  - Runtime:  mcp.php lists and calls only what is listed.
 *  - Display:  surface.php shows the allowlist, forbidden components and
 *              reconciliation status.
 *
 * Pure data structure plus pure functions - no Moodle access except in
 * registered_functions(), so that the check logic itself stays testable.
 *
 * @package    local_coursepilot
 * @copyright  2026 Coursepilot
 * @license    https://www.gnu.org/licenses/agpl-3.0.html GNU AGPL v3 or later
 */
class privacy_surface {

    /** @var string Shortname of the external service from db/services.php. */
    public const SERVICE_SHORTNAME = 'coursepilot';

    /**
     * Positive allowlist: MCP tool name => web service function name.
     *
     * Derived from {@see tool_registry} - the one tool registration
     * (#378). A new tool is only permissible after explicit review
     * - the contract test fails as long as a registered name is missing
     * here or vice versa.
     *
     * @return array<string, string>
     */
    public static function allowed_tools(): array {
        return tool_registry::allowed_tools();
    }

    /**
     * Name components that must not occur in any registered name.
     *
     * They denote learner-data or person surfaces. The scope is
     * **registered names** (tools, web service
     * functions), not internally called PHP functions: an
     * enrol_get_my_courses() in the body of an allowed function is permissible
     * (#300, point 3).
     *
     * "discussion" instead of "forum": creating a forum activity is
     * permitted course design, reading posts is not - Moodle's
     * forum-reading web services are consistently named "...discussion(s)/...posts".
     *
     * @var string[]
     */
    public const FORBIDDEN_TOKENS = [
        'submission',
        'discussion',
        'attempt',
        'participant',
        'enrol',
        'grade',
        'user',
    ];

    /**
     * Is this MCP tool name approved?
     *
     * @param string $toolname
     * @return bool
     */
    public static function is_allowed_tool(string $toolname): bool {
        return isset(self::allowed_tools()[$toolname]);
    }

    /**
     * Web service function for an approved tool name.
     *
     * @param string $toolname
     * @return string|null null if the tool name is not approved.
     */
    public static function function_for_tool(string $toolname): ?string {
        return self::allowed_tools()[$toolname] ?? null;
    }

    /**
     * The web service functions that are actually attached to the
     * Coursepilot service on the running instance.
     *
     * This is the case no repo test can catch: an admin subsequently attaches a
     * function to the service (#300, point 1).
     *
     * @return string[] sorted function names; empty if the service is missing.
     */
    public static function registered_functions(): array {
        global $DB;

        $service = $DB->get_record('external_services', ['shortname' => self::SERVICE_SHORTNAME]);
        if (!$service) {
            return [];
        }
        $names = $DB->get_fieldset_select(
            'external_services_functions',
            'functionname',
            'externalserviceid = :id',
            ['id' => $service->id]
        );
        sort($names);
        return $names;
    }

    /**
     * Reconciles the really registered surface against the allowlist and the
     * forbidden name components.
     *
     * Pure: receives the registered list as input, does not access
     * Moodle itself. Test, runtime and display call the same function.
     *
     * @param string[] $registered Really registered web service function names.
     * @return array<int, array{type: string, name: string, detail: string}>
     *         Empty if the surface conforms to the contract.
     */
    public static function check(array $registered): array {
        $violations = [];
        $allowedtools = self::allowed_tools();
        $allowed = array_values($allowedtools);

        foreach (array_diff($registered, $allowed) as $name) {
            $violations[] = [
                'type' => 'unexpected',
                'name' => $name,
                'detail' => 'Registered, but not in the allowlist.',
            ];
        }

        foreach (array_diff($allowed, $registered) as $name) {
            $violations[] = [
                'type' => 'missing',
                'name' => $name,
                'detail' => 'In the allowlist, but not registered.',
            ];
        }

        // Forbidden components apply to both namespaces: the registered
        // functions and the externally visible tool names.
        $checknames = array_unique(array_merge($registered, array_keys($allowedtools), $allowed));
        foreach ($checknames as $name) {
            foreach (self::FORBIDDEN_TOKENS as $token) {
                if (strpos(strtolower($name), $token) !== false) {
                    $violations[] = [
                        'type' => 'forbidden_token',
                        'name' => $name,
                        'detail' => 'Contains the forbidden component "' . $token . '".',
                    ];
                }
            }
        }

        return $violations;
    }
}
